// This file is generated by packages/shared/scripts/generate-feature-registries.mjs.
// Add a new folder with manifest.ts, then run pnpm --filter @marinara-engine/shared build.
import type { BuiltInAgentManifest } from "./agent-manifest.types.js";


export const BUILT_IN_AGENT_MANIFESTS: readonly BuiltInAgentManifest[] = [
];

