// This file is generated by packages/shared/scripts/generate-feature-registries.mjs.
// Add a new folder with engine.manifest.ts, then run pnpm --filter @marinara-engine/shared build.
import type { AnyTurnGameEngine } from "./engine.types.js";

import { unoGameEngine } from "./uno/engine.manifest.js";
import { chessGameEngine } from "./chess/engine.manifest.js";
import { pokerGameEngine } from "./poker/engine.manifest.js";
import { eightballGameEngine } from "./eightball/engine.manifest.js";
import { ticTacToeGameEngine } from "./tic-tac-toe/engine.manifest.js";
import { rockPaperScissorsGameEngine } from "./rock-paper-scissors/engine.manifest.js";

export const TURN_GAME_ENGINES: readonly AnyTurnGameEngine[] = [
  unoGameEngine,
  chessGameEngine,
  pokerGameEngine,
  eightballGameEngine,
  ticTacToeGameEngine,
  rockPaperScissorsGameEngine,
];

